#Caracteriticas de los objetos o personas o animales o lo q sea
caracteristicas = ["objeto", "persona", "lugar", "vivo", "animal", "tecnologico","famoso",
"natural", "comestible", "transporte", "humano", "lugar_cerrado", "escribir", "entretenimiento",
"pequenio", "grande", "antiguo", "util_diario","humano_creo","semillas","crece_tierra","animal_proviene","escuela","investigacion"
,"aportacion", "actual" ,"1900", "1800", "1700", "1600", "1500","inventor","artista","filosofo", "escritor","musico","politico",
"empresario", "preparado","aprender","pintor","oficina", "ficcion", "animal_domestico", "deporte", "musica", "arte", 
"pelicula", "historia", "espacio", "cientifico", "siglo_XVI", "2000", "inteligente", "activista","nezayork"]

pensamiento = {

	#objetos
	"lapiz" : {"objeto": True, "oficina": True, "escuela": True,  "escribir": True, "humano_creo":True},
	"celular" : {"objeto": True, "tecnologico": True, "util_diario": True, "pequenio": True, "humano_creo": True, "escribir":True,"aprender":True},
	"silla" : {"objeto": True, "humano_creo": True, "util_diario": True},
	"automovil" : {"objeto": True, "transporte": True, "tecnologico":True, "humano_creo": True, "grande":True},
	"balon" : {"objeto": True, "entretenimiento": True, "pequenio": True},
	"teclado" : {"objeto": True, "escribir": True	, "tecnologico": True, "humano_creo": True, "util_diario": True, },
	"reloj" : {"objeto":True, "tecnologico": True, "pequenio": True, "util_diario":True, "humano_creo": True},
	"computadora" : {"objeto": True, "tecnologico":True, "escribir":True, "entretenimiento": True, "util_diario":True,"humano_creo": True,"aprender":True },
	"cubierto" : {"objeto": True,  "util_diario": True, "pequenio": True, "humano_creo":True},
	"television" : {"objeto": True, "tecnologico": True, "entretenimiento": True, "humano_creo": True},
	"fruta" : {"objeto": True, "comestible": True, "natural": True, "semillas":True},
	"verdura" : {"objeto": True, "comestible": True, "natural":True},
	"tuberculo" : {"objeto": True, "comestible": True, "natural":True, "crece_tierra":True},
	"carne" : {"objeto": True, "comestible":True, "natural": True, "animal_proviene": True},
	"botella" : {"objeto":True, "humano_creo":True, "util_diario": True},
	"leche" : {"objeto": True, "animal_proviene": True, "comestible": True, "natural": True},
	"huevo" : {"objeto": True, "animal_proviene": True, "comestible": True, "natural": True, "pequenio": True},
	"sandwich":{"objeto": True, "comestible":True, "preparado":True },
	"taco":{"objeto":True, "comestible":True, "preparado":True},
	"torta":{"objeto":True, "comestible": True, "preparado":True},
	"taza":{"objeto":True, "oficina":True, "escuela":True, "humano_creo":True, "util_diario":True},
	"ventilador": {"objeto": True, "oficina": True, "humano_creo":True, "tecnologico": True, "util_diario":True},
	"libro": {"objeto": True, "oficina":True, "escuela":True, "humano_creo": True, "aprender":True, "pequenio": True},
	"audifonos": {"objeto":True, "oficina":True, "escuela":True,"humano_creo":True, "tecnologico": True, "pequenio": True},
	"libreta": {"objeto": True, "oficina": True, "escuela":True, "humano_creo":True, "escribir":True, "aprender": True},

 	#lugares

	"paris" : {"lugar": True, "famoso": True, "lugar_cerrado": False},
	"playa" : {"lugar": True, "natural": True, "entretenimiento": True},
	"cine" : {"lugar": True, "lugar_cerrado": True, "entretenimiento": True},
	"escuela" : {"lugar": True, "lugar_cerrado": True, "util_diario": True},
	"museo" : {"lugar": True, "lugar_cerrado": True, "antiguo": True},
	"desierto" : {"lugar": True, "natural": True, "grande": True},
	"volcan" : {"lugar": True, "natural": True, "grande": True},
	"oficina" : {"lugar": True, "lugar_cerrado": True, "util_diario": True},
	"parque" : {"lugar": True, "natural": True, "entretenimiento": True},
	"marte" : {"lugar": True, "natural": True, "famoso": True},
	"escom" : {"lugar": True, "escribir":True, "humano_creo":True, "escuela": True, 'investigacion': True, "lugar":True},
	"cic" : {"lugar":True, "escribir": True, "humano_creo":True, "investigacion": True, 'escuela': True, "lugar_cerrado":True},
	"casa": {"lugar": True, "lugar_cerrado": True, "util_diario": True, "humano_creo": True},
	"escuela": {"lugar": True, "lugar_cerrado": True, "util_diario": True, "humano_creo": True, "aprender": True},
	"hospital": {"lugar": True, "lugar_cerrado": True, "util_diario": True, "humano_creo": True},
	"restaurante": {"lugar": True, "lugar_cerrado": True, "util_diario": True, "humano_creo": True},
	"iglesia": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "antiguo": True},
	"templo": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "antiguo": True},
	"biblioteca": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "aprender": True},
	"zoologico": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "entretenimiento": True},
	"acuario": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "entretenimiento": True},
	"estadio": {"lugar": True, "humano_creo": True, "entretenimiento": True, "grande": True},
	"teatro": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "entretenimiento": True, "antiguo": True},
	"catedral": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "antiguo": True},
	"palacio": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "antiguo": True},
	"castillo": {"lugar": True, "lugar_cerrado": True, "humano_creo": True, "antiguo": True},

	#personas
	"Einstein": {"persona": True, "famoso": True, "aportacion": True, "1800": True, "1900": True},
	"Gauss": {"persona": True, "famoso": True, "aportacion": True, "1700":True, "1800": True},
	"Fourier": {"persona": True, "famoso": True, "aportacion":True, "1700":True, "1800":True},
	"Laplace": {"persona": True, "famoso":True, "aportacion":True,"1700":True, "1800": True},
	"Curie": {"persona": True, "famoso": True, "aportacion": True, "cientifico": True, "1900": True},
	"Tesla": {"persona": True, "famoso": True, "aportacion": True, "inventor": True, "cientifico": True, "1800": True, "1900": True},
    "Edison": {"persona": True, "famoso": True, "aportacion": True, "inventor": True, "1800": True, "1900": True},
    "Da Vinci": {"persona": True, "famoso": True, "aportacion": True, "inventor": True, "artista": True, "cientifico": True, "1500": True, "siglo_XVI": True},
	"Picasso": {"persona": True, "famoso": True, "artista": True, "1900": True, "pintor": True},
    "Van Gogh": {"persona": True, "famoso": True, "artista": True, "1800": True, "pintor": True},
    "Camus": {"persona": True, "famoso": True, "escritor": True, "1900": True, "filosofo": True}, 
    "Schopenhauer": {"persona": True, "famoso":True, "escritor":True, "1800":True, "1700": True, "filosofo": True},
    "John Lennon": {"persona": True, "famoso": True, "escritor":True, "1900":True, "artista": True, "musico": True},
    "Thom Yorke": {"persona":True, "famoso":True, "escritor": True, "1900":True, "2000":True, "musico":True, "artista":True},
    "Gustavo Cerati": {"persona":True, "famoso":True, "escritor":True, "1900":True, "2000":True, "musico":True, "artista":True},
  	"Charly Garcia": {"persona": True, "famoso": True, "escritor": True, "1900":True, "2000":True, "musico":True, "artista":True},
  	"AMLO": {"persona":True, "famoso":True, "escritor": True, "politico":True, "1900":True, "2000":True},
  	"Trump": {"persona": True, "famoso":True, "politico":True, "empresario":True, "1900":True, "2000": True},
	"Lionel Messi": {"persona": True, "famoso": True, "deporte": True, "1900": True, "2000": True},
    "Cristiano Ronaldo": {"persona": True, "famoso": True, "deporte": True, "1900": True, "2000": True},
    "Michael Jordan": {"persona": True, "famoso": True, "deporte": True, "1900": True, "2000": True},
    "Shakira": {"persona": True, "famoso": True, "musico": True, "artista": True, "1900": True, "2000": True},
    "Bad Bunny": {"persona": True, "famoso": True, "musico": True, "artista": True, "2000": True},
    "Taylor Swift": {"persona": True, "famoso": True, "musico": True, "escritor": True, "artista": True, "2000": True},
    "Beyonce": {"persona": True, "famoso": True, "musico": True, "artista": True, "1900": True, "2000": True},
    "Elon Musk": {"persona": True, "famoso": True, "empresario": True, "tecnologico": True, "2000": True},
    "Bill Gates": {"persona": True, "famoso": True, "empresario": True, "aportacion": True, "1900": True, "2000": True},
    "Mark Zuckerberg": {"persona": True, "famoso": True, "empresario": True, "tecnologico": True, "2000": True},
    "Barack Obama": {"persona": True, "famoso": True, "politico": True, "1900": True, "2000": True},
    "Vladimir Putin": {"persona": True, "famoso": True, "politico": True, "1900": True, "2000": True},
    "Volodymyr Zelensky": {"persona": True, "famoso": True, "politico": True, "2000": True},
    "Malala Yousafzai": {"persona": True, "famoso": True, "aportacion": True, "activista": True, "2000": True},
    "Greta Thunberg": {"persona": True, "famoso": True, "activista": True, "2000": True},
    "beatles": {"persona": True, "entretenimiento": True, "musica": True, "famoso": True},
	"queen": {"persona": True, "entretenimiento": True, "musica": True, "famoso": True},
	"metallica": {"persona": True, "entretenimiento": True, "musica": True, "famoso": True},
	"mozart": {"persona": True, "musica": True, "famoso": True, "antiguo": True},
	"beethoven": {"persona": True, "musica": True, "famoso": True, "antiguo": True},
	"bach": {"persona": True, "musica": True, "famoso": True, "antiguo": True},
	"chopin": {"persona": True, "musica": True, "famoso": True, "antiguo": True},
	"tchaikovsky": {"persona": True, "musica": True, "famoso": True, "antiguo": True},
	"lady gaga": {"persona": True, "musica": True, "famoso": True},
	"rihanna": {"persona": True, "musica": True, "famoso": True},
	"drake": {"persona": True, "musica": True, "famoso": True},
	"justin bieber": {"persona": True, "musica": True, "famoso": True},
	"the weeknd": {"persona": True, "musica": True, "famoso": True},
	"Kabezuko" : {"persona": True, "vivo": True, "musica":True, "inteligente": True, "2000":True, "artista": True,"nezayork": True},
    # Animales
    "perro": {"animal": True, "vivo": True, "animal_domestico": True},
    "gato": {"animal": True, "vivo": True, "animal_domestico": True},
    "leon": {"animal": True, "vivo": True, "grande": True, "natural": True},
    "aguila": {"animal": True, "vivo": True, "natural": True},
    "elefante": {"animal": True, "vivo": True, "grande": True, "natural": True},
    "tigre": {"animal": True, "vivo": True, "grande": True, "natural": True},
    "caballo": {"animal": True, "vivo": True, "animal_domestico": True, "grande": True},
    "vaca": {"animal": True, "vivo": True, "animal_domestico": True, "animal_proviene": True},
    "pollo": {"animal": True, "vivo": True, "animal_domestico": True, "animal_proviene": True},
    "conejo": {"animal": True, "vivo": True, "animal_domestico": True, "pequenio": True},
    "oso": {"animal": True, "vivo": True, "grande": True, "natural": True},
    "delfin": {"animal": True, "vivo": True, "natural": True, "inteligente": True},
    "ballena": {"animal": True, "vivo": True, "grande": True, "natural": True},
    "jirafa": {"animal": True, "vivo": True, "grande": True, "natural": True},
	"serpiente": {"animal": True, "vivo": True, "natural": True},
    "tortuga": {"animal": True, "vivo": True, "natural": True, "pequenio": True},
	"pez": {"animal": True, "vivo": True, "natural": True, "pequenio": True},	
	"hamster": {"animal": True, "vivo": True, "animal_domestico": True, "pequenio": True},
    "iguana": {"animal": True, "vivo": True, "natural": True, "pequenio": True},	
    "pajaro": {"animal": True, "vivo": True, "natural": True, "pequenio": True},
    "loro": {"animal": True, "vivo": True, "animal_domestico": True, "pequenio": True},
    "zorro": {"animal": True, "vivo": True, "natural": True, "pequenio": True},
    "mapache": {"animal": True, "vivo": True, "natural": True, "pequenio": True},
    "canguro": {"animal": True, "vivo": True, "natural": True, "pequenio": True},
    "mono": {"animal": True, "vivo": True, "natural": True, "inteligente": True},
    "chimpance": {"animal": True, "vivo": True, "natural": True, "inteligente": True},
    "gorila": {"animal": True, "vivo": True, "natural": True, "inteligente": True},
    "hipopotamo": {"animal": True, "vivo": True, "natural": True, "grande": True},
    "rinoceronte": {"animal": True, "vivo": True, "natural": True, "grande": True},
    "lobo": {"animal": True, "vivo": True, "natural": True, "inteligente": True},
    "zebra": {"animal": True, "vivo": True, "natural": True, "grande": True},
    "ciervo": {"animal": True, "vivo": True, "natural": True, "grande": True},
    "búho": {"animal": True, "vivo": True, "natural": True, "pequenio": True},
    
	# Comida
	"manzana": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"banana": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"naranja": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"tomate": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"lechuga": {"objeto": True, "comestible": True, "natural": True},
	"papa": {"objeto": True, "comestible": True, "natural": True, "crece_tierra": True},
	"zanahoria": {"objeto": True, "comestible": True, "natural": True, "crece_tierra": True},
	"pollo_crudo": {"objeto": True, "comestible": True, "natural": True, "animal_proviene": True},
	"res_cruda": {"objeto": True, "comestible": True, "natural": True, "animal_proviene": True},
	"pescado_crudo": {"objeto": True, "comestible": True, "natural": True, "animal_proviene": True},
	"queso": {"objeto": True, "comestible": True, "animal_proviene": True},
	"yogur": {"objeto": True, "comestible": True, "animal_proviene": True},
	"hamburguesa": {"objeto": True, "comestible": True, "preparado": True},
	"pizza": {"objeto": True, "comestible": True, "preparado": True},
	"ensalada": {"objeto": True, "comestible": True, "preparado": True},
	"sopa": {"objeto": True, "comestible": True, "preparado": True},
	"pasta": {"objeto": True, "comestible": True, "preparado": True},
	"arroz": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"frijoles": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
    "lentejas": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"nueces": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"almendras": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"cacahuates": {"objeto": True, "comestible": True, "natural": True, "semillas": True},
	"chocolate": {"objeto": True, "comestible": True, "preparado": True},
	"helado": {"objeto": True, "comestible": True, "preparado": True},
	"pastel": {"objeto": True, "comestible": True, "preparado": True},
	"galletas": {"objeto": True, "comestible": True, "preparado": True},
	"pan": {"objeto": True, "comestible": True, "preparado": True},
    "taco": {"objeto": True, "comestible": True, "preparado": True},
    "burrito": {"objeto": True, "comestible": True, "preparado": True},
    "quesadilla": {"objeto": True, "comestible": True, "preparado": True},
    "enchilada": {"objeto": True, "comestible": True, "preparado": True},
    "tamales": {"objeto": True, "comestible": True, "preparado": True},
    "chilaquiles": {"objeto": True, "comestible": True, "preparado": True},
    "pozole": {"objeto": True, "comestible": True, "preparado": True},
    "mole": {"objeto": True, "comestible": True, "preparado": True},
    "ceviche": {"objeto": True, "comestible": True, "preparado": True},
    "sushi": {"objeto": True, "comestible": True, "preparado": True},

	# Medios de transporte
	"bicicleta": {"objeto": True, "transporte": True, "humano_creo": True, "pequenio": True},
	"moto": {"objeto": True, "transporte": True, "tecnologico": True, "humano_creo": True, "pequenio": True},
	"avion": {"objeto": True, "transporte": True, "tecnologico": True, "humano_creo": True, "grande": True},
	"barco": {"objeto": True, "transporte": True, "tecnologico": True, "humano_creo": True, "grande": True},
	"tren": {"objeto": True, "transporte": True, "tecnologico": True, "humano_creo": True, "grande": True},
    
    # Deportes
    "futbol": {"entretenimiento": True, "deporte": True},
    "basquetbol": {"entretenimiento": True, "deporte": True},
    "ajedrez": {"entretenimiento": True, "deporte": True, "aprender": True},
    "tenis": {"entretenimiento": True, "deporte": True},
    "natacion": {"entretenimiento": True, "deporte": True},
    "ciclismo": {"entretenimiento": True, "deporte": True},
    "atletismo": {"entretenimiento": True, "deporte": True},
    "voleibol": {"entretenimiento": True, "deporte": True},
    "boxeo": {"entretenimiento": True, "deporte": True},
    "golf": {"entretenimiento": True, "deporte": True},
    "beisbol": {"entretenimiento": True, "deporte": True},
    "rugby": {"entretenimiento": True, "deporte": True},
    "esgrima": {"entretenimiento": True, "deporte": True},
	"esqui": {"entretenimiento": True, "deporte": True},
    "surf": {"entretenimiento": True, "deporte": True},
	"snowboard": {"entretenimiento": True, "deporte": True},
    "karate": {"entretenimiento": True, "deporte": True},
	"taekwondo": {"entretenimiento": True, "deporte": True},
	"judo": {"entretenimiento": True, "deporte": True},
	"mma": {"entretenimiento": True, "deporte": True},
    "crossfit": {"entretenimiento": True, "deporte": True},
	"pilates": {"entretenimiento": True, "deporte": True},
	"yoga": {"entretenimiento": True, "deporte": True},
    "halterofilia": {"entretenimiento": True, "deporte": True},
	"escalada": {"entretenimiento": True, "deporte": True},
	"paracaidismo": {"entretenimiento": True, "deporte": True},
	"bmx": {"entretenimiento": True, "deporte": True},
	"motocross": {"entretenimiento": True, "deporte": True},
	"automovilismo": {"entretenimiento": True, "deporte": True},
	"f1": {"entretenimiento": True, "deporte": True},
	"nascar": {"entretenimiento": True, "deporte": True},
	"rally": {"entretenimiento": True, "deporte": True},

    # Instrumentos musicales
    "guitarra": {"objeto": True, "musica": True, "humano_creo": True},
    "piano": {"objeto": True, "musica": True, "humano_creo": True, "grande": True},
    "bateria": {"objeto": True, "musica": True, "humano_creo": True, "grande": True},
    "violin": {"objeto": True, "musica": True, "humano_creo": True},
    "flauta": {"objeto": True, "musica": True, "humano_creo": True, "pequenio": True},
    "trompeta": {"objeto": True, "musica": True, "humano_creo": True},
    "saxofon": {"objeto": True, "musica": True, "humano_creo": True},
    "arpa": {"objeto": True, "musica": True, "humano_creo": True, "grande": True},
    "ukelele": {"objeto": True, "musica": True, "humano_creo": True, "pequenio": True},
    "acordeon": {"objeto": True, "musica": True, "humano_creo": True},
    "tambor": {"objeto": True, "musica": True, "humano_creo": True},
    "clarinete": {"objeto": True, "musica": True, "humano_creo": True},
	"contrabajo": {"objeto": True, "musica": True, "humano_creo": True, "grande": True},
    "trombon": {"objeto": True, "musica": True, "humano_creo": True},
    "oboe": {"objeto": True, "musica": True, "humano_creo": True},
	"metronomo": {"objeto": True, "musica": True, "humano_creo": True, "pequenio": True},
    "melodica": {"objeto": True, "musica": True, "humano_creo": True, "pequenio": True},
	"armonica": {"objeto": True, "musica": True, "humano_creo": True, "pequenio": True},
    "cello": {"objeto": True, "musica": True, "humano_creo": True, "grande": True},
    "sintetizador": {"objeto": True, "musica": True, "humano_creo": True, "tecnologico": True, "pequenio": True},
    "dj": {"objeto": True, "musica": True, "humano_creo": True, "tecnologico": True, "pequenio": True},
    "bajo": {"objeto": True, "musica": True, "humano_creo": True},

    # Cultura y arte
    "mona lisa": {"objeto": True, "arte": True, "antiguo": True, "famoso": True},
    "coliseo romano": {"lugar": True, "historia": True, "antiguo": True, "famoso": True},
    "la noche estrellada": {"objeto": True, "arte": True, "famoso": True, "pintor": True},
    "capilla sixtina": {"lugar": True, "arte": True, "antiguo": True, "famoso": True},
    "piramides de egipto": {"lugar": True, "historia": True, "antiguo": True, "famoso": True},
    "muralla china": {"lugar": True, "historia": True, "antiguo": True, "famoso": True},
    "taj mahal": {"lugar": True, "historia": True, "famoso": True, "arte": True},
    "guernica": {"objeto": True, "arte": True, "famoso": True, "pintor": True},
    "david de miguel angel": {"objeto": True, "arte": True, "antiguo": True, "famoso": True},
    "partenon": {"lugar": True, "historia": True, "antiguo": True, "famoso": True},
    "machu picchu": {"lugar": True, "historia": True, "antiguo": True, "famoso": True},
    "cristo redentor": {"lugar": True, "historia": True, "famoso": True, "arte": True},
    "sistine chapel": {"lugar": True, "arte": True, "antiguo": True, "famoso": True},
    "la ultima cena": {"objeto": True, "arte": True, "antiguo": True, "famoso": True, "pintor": True},
    "el pensador": {"objeto": True, "arte": True, "antiguo": True, "famoso": True},
	"la joven de la perla": {"objeto": True, "arte": True, "antiguo": True, "famoso": True, "pintor": True},
    "el beso": {"objeto": True, "arte": True, "famoso": True, "pintor": True},
    "el grito": {"objeto": True, "arte": True, "famoso": True, "pintor": True},
    "la creacion de adan": {"objeto": True, "arte": True, "antiguo": True, "famoso": True, "pintor": True},
    
    # Ficción
    "harry potter": {"persona": True, "ficcion": True, "famoso": True},
    "batman": {"persona": True, "ficcion": True, "famoso": True},
    "star wars": {"entretenimiento": True, "pelicula": True, "ficcion": True},
    "superman": {"persona": True, "ficcion": True, "famoso": True},
    "spiderman": {"persona": True, "ficcion": True, "famoso": True},
    "iron man": {"persona": True, "ficcion": True, "famoso": True, "tecnologico": True},
    "sherlock holmes": {"persona": True, "ficcion": True, "famoso": True},
    "frodo": {"persona": True, "ficcion": True, "famoso": True},
    "gandalf": {"persona": True, "ficcion": True, "famoso": True},
    "darth vader": {"persona": True, "ficcion": True, "famoso": True},
    "goku": {"persona": True, "ficcion": True, "famoso": True},
    "naruto": {"persona": True, "ficcion": True, "famoso": True},
	"luffy": {"persona": True, "ficcion": True, "famoso": True},
    "tony stark": {"persona": True, "ficcion": True, "famoso": True, "tecnologico": True},
	"capitan america": {"persona": True, "ficcion": True, "famoso": True},
	"black widow": {"persona": True, "ficcion": True, "famoso": True},
	"hulk": {"persona": True, "ficcion": True, "famoso": True},
	"thor": {"persona": True, "ficcion": True, "famoso": True},
	"loki": {"persona": True, "ficcion": True, "famoso": True},
	"wanda maximoff": {"persona": True, "ficcion": True, "famoso": True},
	"doctor strange": {"persona": True, "ficcion": True, "famoso": True, "tecnologico": True},
	"black panther": {"persona": True, "ficcion": True, "famoso": True},
	"aquaman": {"persona": True, "ficcion": True, "famoso": True},

    # Tecnología avanzada
    "internet": {"objeto": False, "tecnologico": True, "util_diario": True, "famoso": True},
    "dron": {"objeto": True, "tecnologico": True, "humano_creo": True, "pequenio": True},
    "satelite": {"objeto": True, "tecnologico": True, "humano_creo": True, "grande": True, "espacio": True},
    "robot": {"objeto": True, "tecnologico": True, "humano_creo": True},
    "cohete espacial": {"objeto": True, "tecnologico": True, "espacio": True, "grande": True, "humano_creo": True},
    "inteligencia artificial": {"objeto": False, "tecnologico": True, "famoso": True},
    "nanotecnologia": {"objeto": False, "tecnologico": True, "famoso": True},
    "realidad virtual": {"objeto": False, "tecnologico": True, "entretenimiento": True},
    "impresora 3d": {"objeto": True, "tecnologico": True, "humano_creo": True},
    "microchip": {"objeto": True, "tecnologico": True, "humano_creo": True, "pequenio": True},
    "wifi": {"objeto": False, "tecnologico": True, "util_diario": True},
    "blockchain": {"objeto": False, "tecnologico": True, "famoso": True},
	"criptomoneda": {"objeto": False, "tecnologico": True, "famoso": True},
    "bitcoin": {"objeto": False, "tecnologico": True, "famoso": True},
    "ethereum": {"objeto": False, "tecnologico": True, "famoso": True},
	"tesla model s": {"objeto": True, "tecnologico": True, "humano_creo": True, "transporte": True, "famoso": True},
	"tesla cybertruck": {"objeto": True, "tecnologico": True, "humano_creo": True, "transporte": True, "famoso": True},
	"spacex": {"objeto": False, "tecnologico": True, "famoso": True, "espacio": True},
	"starlink": {"objeto": False, "tecnologico": True, "famoso": True, "espacio": True},
	"neuralink": {"objeto": False, "tecnologico": True, "famoso": True},
	"hyperloop": {"objeto": False, "tecnologico": True, "famoso": True, "transporte": True},
    
	#Sentimientos y emociones
    "felicidad": {"sentimiento": True, "positivo": True, "comun": True},
    "amor": {"sentimiento": True, "positivo": True, "intenso": True, "comun": True},
    "esperanza": {"sentimiento": True, "positivo": True},
    "gratitud": {"sentimiento": True, "positivo": True, "comun": True},
    "tristeza": {"sentimiento": True, "negativo": True, "comun": True},
    "miedo": {"sentimiento": True, "negativo": True, "intenso": True, "comun": True},
    "enojo": {"sentimiento": True, "negativo": True, "intenso": True, "comun": True},
    "soledad": {"sentimiento": True, "negativo": True},
    "sorpresa": {"sentimiento": True, "intenso": True, "comun": True},
    "orgullo": {"sentimiento": True, "positivo": True, "intenso": True},
    "vergüenza": {"sentimiento": True, "negativo": True, "comun": True},
    "culpa": {"sentimiento": True, "negativo": True, "comun": True},
	"calma": {"sentimiento": True, "positivo": True},
	"ansiedad": {"sentimiento": True, "negativo": True, "intenso": True, "comun": True},
	"confianza": {"sentimiento": True, "positivo": True, "comun": True},
	"desesperación": {"sentimiento": True, "negativo": True, "intenso": True},
	"ilusión": {"sentimiento": True, "positivo": True, "comun": True},
	"nostalgia": {"sentimiento": True, "negativo": True},
	"compasión": {"sentimiento": True, "positivo": True},
	"empatía": {"sentimiento": True, "positivo": True, "comun": True},
	"celos": {"sentimiento": True, "negativo": True, "comun": True},
	"envidia": {"sentimiento": True, "negativo": True, "comun": True},
	"admiración": {"sentimiento": True, "positivo": True, "comun": True},
	"frustración": {"sentimiento": True, "negativo": True, "comun": True},
	"alivio": {"sentimiento": True, "positivo": True, "comun": True},
}

preguntas = {
	"objeto" :"¿Es un objeto fisico? (s/n): ",
	"persona" : "¿Es una persona real o ficticia? (s/n): ",
	"lugar" : "¿Es un lugar? (s/n): ",
	"animal":  "¿Es algun tipo de animal? (s/n): " ,
	"vivo": "¿Es algo que esta o estuvo vivo? (s/n): ",
	"tecnologico": "¿Esta relacionado con la tecnologia? (s/n): ",
	"famoso": "¿Es algun lugar o persona famosos? (s/n): ",
	"natural": "¿Es algo que se obtiene directamente de la naturaleza? (s/n): ",
	"comestible": "¿Es algo comestible para el ser humano? (s/n): ",
	"transporte": "¿Es algun medio de transporte? (s/n): ",
	"humano": "¿Es un ser humano? (s/n): ",
	"lugar_cerrado": "¿Es un lugar cerrado (no cuenta con espacios abiertos) ? (s/n): ",
	"escribir": "¿Sirve para escribir, o se puede escribir en el? (s/n): ",
	"entretenimiento": "¿Es alguna forma de entretenimiento? (s/n): ",
	"pequenio": "¿Es un objeto pequenio? (s/n): ",
	"grande": "¿Es un objeto grande? (s/n): ",
	"antiguo": "¿Es algo antiguo o historico? (s/n): ",
	"util_diario": "¿Es algo que se le puede sacar provecho en el dia a dia (una herramienta)? (s/n): ",
	"humano_creo": "¿Fue creado por los humanos? (s/n): ",
	"semillas": "¿Contiene semillas? (s/n): ",
	"crece_tierra": "¿Es algo que crece dentro de la tierra(bajo tierra)? (s/n): ",
	"animal_proviene": "¿Es algo que proviene de un animal? (s/n): ",
	"escuela": "¿Es una escuela? (s/n): ",
	"investigacion": "¿Es un centro de investigacion? (s/n): ",
	"aportacion": "¿La persona hizo alguna aportacion a la ciencia o tecnologia? (s/n): ",
	"actual" : "¿La persona es de la epoca contemporane (1980-2025)? (s/n): ",
	"1900": "¿La persona estuvo vivo durante los anios entre  1900-1980? (s/n): ",
	"1800": "¿La persona estuvo vivo durante los anios entre 1800-1900? (s/n): ",
	"1700": "¿La persona estuvo vivo durante los anios entre 1700-1800? (s/n): ",
	"1600": "¿La persona estuvo vivo durante los anios entre 1600-1700? (s/n): ",
	"1500": "¿La persona estuvo vivo durante los anios entre 1500-1600? (s/n): ",
	"inventor": "¿La persona invento algo tangible? (s/n): ",
	"artista": "¿La persona es algun tipo de artista? (s/n): ",
	"escritor": "¿La persona es un escritor? (s/n): ",
	"filosofo":"¿La persona es un filosofo? (s/n): ",
	"musico": "¿La persona es un musico? (s/n): ",	
	"politico": "¿La persona es un politico o esta relacionad con la politica? (s/n):",
	"empresario": "¿La persona es un empresario? (s/n):",
	"preparado": "¿Es un alimento preparado? (s/n):",
	"aprender": "¿Es un objeto que sirve para aprender? (s/n): ",
	"pintor": "¿La persona es un pintor? (s/n): ",
	"oficina": "¿El objeto se puede encontrar en alguna oficina	? (s/n): ",
    "ficcion": "¿Pertenece al mundo de la ficción? (s/n): ",
    "animal_domestico": "¿Es un animal doméstico? (s/n): ",
    "deporte": "¿Es un deporte? (s/n): ",
    "musica": "¿Está relacionado con la música? (s/n): ",
    "arte": "¿Está relacionado con el arte? (s/n): ",
    "pelicula": "¿Es una película? (s/n): ",
    "historia": "¿Está relacionado con la historia? (s/n): ",
    "espacio": "¿Está relacionado con el espacio exterior? (s/n): ",
    "sentimiento": "¿Es un sentimiento o emoción? (s/n): ",
    "positivo": "¿Es un sentimiento positivo? (s/n): ",
    "negativo": "¿Es un sentimiento negativo? (s/n): ",
    "intenso": "¿Es un sentimiento muy intenso? (s/n): ",
    "comun": "¿Es un sentimiento común en la mayoría de las personas? (s/n): ",
    "nezayork": "¿la persona vive, vivio o es originario de nezayork? (s/n)",
	}

